Restart
We forked scratch-gui repository from TurboWarp/scratch-gui instead of Clone&Modified repository.This will bring many benefits.

Sorry, but all previous commit history will be lost.
🙏🙏🙏

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -10,13 +10,40 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    
+    - name: Set up JDK 11
+      uses: actions/setup-java@v3
       with:
-        persist-credentials: false
+        java-version: '11'
+        distribution: 'temurin'
+
     - name: Install Node.js
       uses: actions/setup-node@v4
       with:
-        node-version: 22
+        node-version: 20
         cache: npm
-    - run: npm ci
-    - run: npm run build
-    - run: npm run test:unit
+
+    - name: Install Dependencies
+      run: npm install --ignore-scripts --legacy-peer-deps
+
+    - name: Build scratch-blocks manually
+      run: |
+        cd node_modules/scratch-blocks
+        
+        npm install --no-save google-closure-compiler
+        
+        export PATH=$PWD/node_modules/.bin:$PATH
+        
+        echo "Checking compiler path..."
+        ls -l $PWD/node_modules/.bin/google-closure-compiler || echo "Compiler not found!"
+        which google-closure-compiler || echo "Command not in PATH"
+        
+        node universal-python.js build.py
+    - name: Install microbit
+      run: npm install
+    - name: Build GUI
+      run: |
+        npm run build
+        
+    - name: Run Tests
+      run: npm run test:unit
